version: '3.9'


services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: groot
#    image: maven:3.8.5-openjdk-11
#    volumes:
#      - .:/app
#    working_dir: /app
#    # command: mvn package && java -jar /target/core-java-0.0.1-SNAPSHOT-spring-boot.jar
#    command: mvn spring-boot:run
#    ports:
#      - 5555:8080

volumes:
  data:
    driver: local


